// <auto-generated />
namespace EmployeeManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmmployeeDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmmployeeDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202403050932208_EmmployeeDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
